### ISSUE TITLE
cache bust the json files

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt-docs#10]
These files should _never_ be cached.

Use a url parameter with the current timestamp when fetching the json files to bust the browser cache.

**Comment by sfc-gh-afedorov** [comment]
Why shouldn't they be cached? Seems if they haven't changed since the last time the page was loaded, getting a [304 Not Modified](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304) can save us ~30MB, which is a chunk of load time for a lot of folks on a globally distributed team.
