### ISSUE TITLE
Document schema of catalog.json, run_results.json, manifest.json

### ISSUE THREAD

**Issue by safareli** [fishtown-analytics/dbt-docs#161]
### Describe the feature
As dbt is getting more and more popular, people are building on top of it. It's becoming more and more important to specify schema of catalog.json, run_results.json, manifest.json. probably adding integration tests which assert that those files actually conform to the schema would be nice too to make sure they don't go out of sync

### Describe alternatives you've considered
There are no alternatives.

### Additional context
By schema I mean JSON-schema or typescript definitions or anything like it. as long as we have some schema which would be up to date, people can then convert one schema representation to other. 

[app.quicktype.io](https://app.quicktype.io/) might be helpful to generate initial schema from sample JSON itself and then refine it..

### Who will this benefit?
People working automations and tools on top of dbt will be able to know what the structure of those files is exactly. they will be able to write correct software, which is especially important to the users of dbt as they are working on critically important data.

### Are you interested in contributing this feature?
I think this is something library authors will be able to do most effectively. I can review the changes. also if you were to implement it using JSON scheme I would volunteer to convert it to typescript definitions (that's what I actually want in the end).

**Comment by jtcohen6** [comment]
@safareli You'll be pleased to know that we're version controlling these artifacts, and hosting their JSONSchemas, starting in the next version of dbt (v0.19.0). E.g. you can find:
- The v0 of run results, as it existed in v0.18.1: https://schemas.getdbt.com/dbt/run-results/v0.json
- The v1 of run results, coming in v0.19: https://schemas.getdbt.com/dbt/run-results/v1.json

See [prerelease docs](https://next.docs.getdbt.com/reference/artifacts/dbt-artifacts/) for more details.

**Comment by safareli** [comment]
Thanks, that's great!
