### ISSUE TITLE
Option to quickly deselect tags in full-screen DAG filter

### ISSUE THREAD

**Issue by aaronsteers** [fishtown-analytics/dbt-docs#169]
### Describe the feature

Background:

Once a project has a large number of tags, it becomes overly cumbersome to use the bottom-panel tag filter. For example, our project contains about 20 distinct tags, which means it takes at least 21 clicks to select a single label in the filter panel.

Request:

1. Ideally, there would be a "select/deselect all" option at the top or bottom of the filter panel to allow this be performed more quickly.
2. Alternatively, the filter panel could default to single-select mode - perhaps supporting control-click or shift-click for multiselect.

### Describe alternatives you've considered

n/a

### Additional context

As mentioned above, our project has 20 tags. Including the option for "untagged". this means to select a single tag, we need 21 clicks: 1 click to open the panel, 20 clicks to deselect items, 1 click to close the filter panel, and 1 click (or keyboard "Enter") to filter. So, approximately 23 clicks to change the filter to a single tag.

### Who will this benefit?

Any mature project with a large number of tags would benefit from this feature.

### Are you interested in contributing this feature?

Yes - would be happy to!

**Comment by jtcohen6** [comment]
> Ideally, there would be a "select/deselect all" option at the top or bottom of the filter panel to allow this be performed more quickly.

Hey @aaronsteers, I believe this is coming in v0.19.0 (https://github.com/fishtown-analytics/dbt-docs/issues/98, https://github.com/fishtown-analytics/dbt-docs/pull/138). You can try it out by installing the release candidate:
```
pip install dbt==0.19.0rc2
```

**Comment by aaronsteers** [comment]
@jtcohen6 - That's fantastic! Apologies for the duplicate issue. I'm excited to test this out in 0.19. 

Thanks so much!
