### ISSUE TITLE
minor cleanup of formatting in additional details row

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt-docs#17]
<img width="345" alt="Screen Shot 2019-03-21 at 1 53 31 PM" src="https://user-images.githubusercontent.com/2341841/54773820-bb618a00-4be0-11e9-950e-1cf50edb4a32.png">

Two small things: 

- add commas 
- show units for "size". is that in...kb? maybe denominate it in GB instead?

**Comment by drewbanin** [comment]
@jthandy this varies by database -- is this on Snowflake?

**Comment by jthandy** [comment]
yep! that was on snowflake.

**Comment by drewbanin** [comment]
Fixed in https://github.com/fishtown-analytics/dbt-docs/pull/28
