### ISSUE TITLE
Ability to opt-out of tracking

### ISSUE THREAD

**Issue by w0ut0** [fishtown-analytics/dbt-docs#187]
### Describe the feature
There is currently no (that I know of) way to disable the built-in tracking. It would be nice if there was an opt-out (a flag in `dbt docs generate` maybe?).

We are working in a sensitive environment (healthcare), and this tracking code raises some eyebrows at our clients.

### Describe alternatives you've considered
We could add the tracking domains to a blacklist, but it will still show up as being blocked in the browser.
Alternative is a separate web app to host the documentation, but this one is great!

### Additional context
na

### Who will this benefit?
This will help self-hosted dbt documentation sites (we host ours on [Azure static websites](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website)).

### Are you interested in contributing this feature?
Not really versed in the JavaScript/frontend world, but we could find someone in our team to try to contribute this feature.

**Comment by drewbanin** [comment]
hey @w0ut0 - thanks for opening this issue! You can currently opt out of anonymous usage tracking in dbt by adding the following lines to your `~/.dbt/profiles.yml` file:

```
config:
    send_anonymous_usage_stats: False
```

When this value is set to `False`:
 - dbt Core will not fire anonymous usage stats
 - The docs website _generated_ from this profile will not fire anonymous usage stats

You can find more info on this [in the docs](https://docs.getdbt.com/reference/profiles.yml#send_anonymous_usage_stats). Hope this helps!

**Comment by w0ut0** [comment]
Hi @drewbanin,
didn't know this also applied to the tracking on the documentation site.

Thanks a lot!

**Comment by polmonso** [comment]
Ups, I posted to the old issue. It's a duplicate of https://github.com/dbt-labs/dbt-core/issues/399
