### ISSUE TITLE
Dbt docs "search" includes field matches

### ISSUE THREAD

**Issue by mattarderne** [fishtown-analytics/dbt-docs#22]
### Feature description
In the "search for models" search bar of the DBT Docs, it would be great to be able to search for fields, as currently it seems only to be possible to search by models.

### Who will this benefit?
This would benefit business users (and data engineers) in that they would be able to determine if a field is available in the data warehouse and if it is, to see in which models it lives.

**Comment by drewbanin** [comment]
Hey @mattarderne - I transferred this issue to the `dbt-docs` repo. We track feature requests and bug reports (as well as do development) against this repo.

Thanks for the suggestion - it's a really good idea :)

**Comment by mattarderne** [comment]
Great! 

I have used [Denodo's Data Catalog](https://community.denodo.com/tutorials/browse/datadiscovery/1datacatalogintro) quite extensively in the past and noticed that was a feature there that may prove quite useful for dbt :)

**Comment by rmgpinto** [comment]
I just opened a PR regarding this issue: [Pull Request 23](https://github.com/fishtown-analytics/dbt-docs/pull/23)

**Comment by drewbanin** [comment]
Closed by: https://github.com/fishtown-analytics/dbt-docs/pull/23
