### ISSUE TITLE
Render documentation for seed files

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/dbt-docs#25]
Seed files do not show in the side panel.
You _can_ get to their docs by right clicking on the node in the DAG, and selecting "View Documentation". However, if you have documentation/tests for the seed files, it won't be rendered here.
Related to #15

**Comment by shedd** [comment]
It would be nice if there was a way to enhance the documentation with descriptions through a schema.yml file in the seed directory, as well. While I was able to find the documentation for my seed file as described above, DBT did not parse in the associated description from the schema.yml file that I added to the seed directory. The description on the page says `This seed is not currently documented`
