### ISSUE TITLE
Export model graph to file

### ISSUE THREAD

**Issue by andreissov** [fishtown-analytics/dbt-docs#29]
When running `dbt docs generate` is it possible to add an "Export to file..." button with options for PNG and PDF? 

It would be extremely useful when sharing the model overview with other people, and general documentation outside of dbt.

**Comment by drewbanin** [comment]
Thanks for making this issue @andreissov! I think the graph viz library we use, Cytoscape, supports [exporting a graph to a png](http://js.cytoscape.org/#cy.png).

We should be able to add another item to the [right-click context menu](https://github.com/fishtown-analytics/dbt-docs/blob/master/src/app/components/graph/graph-viz.js#L208) which generates a png and either 1) downloads the image or 2) opens the image in a new tab.
