### ISSUE TITLE
Document macros

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt-docs#61]
Macros should appear in the docs site and be documentable

**Comment by tayloramurphy** [comment]
I would love this! We've resorted to self-documenting in the repo https://gitlab.com/gitlab-data/analytics/blob/master/transform%2Fsnowflake-dbt%2Fmacros%2FREADME.md

Key features for us here:

* Code source (of course)
* Description of what it does
* Models it's used in

Additional thought - unit tests on these would be great 😄

**Comment by drewbanin** [comment]
see https://github.com/fishtown-analytics/dbt/pull/2103/
