### ISSUE TITLE
Add analyses to dependency graph

### ISSUE THREAD

**Issue by alexisprince1994** [fishtown-analytics/dbt-docs#65]
Currently, analyses that are defined in the `analysis` folder of a DBT project do not appear in the dependency graph that gets generated. It would be fantastic to have a way to link an analysis to its dependent model. Any change that gets made regarding this should ensure that analyses that don't depend on DBT models should be able to be represented well as people will version control their SQL queries as analysis during a migration into using DBT more.

It would be fantastic if it were possible to use some visual differentiator between models and analysis.

**Comment by drewbanin** [comment]
this is shipping in dbt v0.16.0 :) 

https://deploy-preview-77--eloquent-tesla-2c6e1b.netlify.com/#!/analysis/analysis.jaffle_shop.my_analysis
