### ISSUE TITLE
feature request: discover data by column

### ISSUE THREAD

**Issue by DanielJSwift** [fishtown-analytics/dbt-docs#8]
**The idea in brief:**

To improve data discovery users can search by column name to find related tables.

As an analogy, this would be similar to querying `information_schema.columns`, `where column_name ilike '%your_string%'`

**Comment by drewbanin** [comment]
See this issue: https://github.com/fishtown-analytics/dbt-docs/issues/22
Closed by: https://github.com/fishtown-analytics/dbt-docs/pull/23
